<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'Reloj vintage',
                'description' => 'Un reloj de pared vintage de los años 50s.',
                'price' => 461.66,
                'image_url' => 'https://i.ebayimg.com/images/g/F78AAOSwCKNkVim1/s-l1200.png',
                'affiliate_link' => 'https://www.ebay.com/itm/394610118472',
                'category_id' => 3,
                'brand_id' => 1,
                'created_at' => Carbon::parse('2025-03-13 23:13:36'),
                'updated_at' => Carbon::parse('2025-03-13 23:13:36'),
            ],
            [
                'name' => 'Máquina de escribir retro',
                'description' => 'Máquina de escribir en perfecto estado',
                'price' => 1700.00,
                'image_url' => 'https://m.media-amazon.com/images/I/81AfEM1H1-L._AC_SL1500_.jpg',
                'affiliate_link' => 'https://www.ubuy.com.mx/sp/product/1GFOT5FS-besportble-vintage-typewriter-model-retro-typewriter-iron-art-typewriter-manual-typewriter-photo-pro',
                'category_id' => 2,
                'brand_id' => 2,
                'created_at' => Carbon::parse('2025-03-13 23:13:36'),
                'updated_at' => Carbon::parse('2025-03-13 23:13:36'),
            ],
            [
                'name' => 'Radio',
                'description' => 'Una radio antigua en perfecto estado.',
                'price' => 500.00,
                'image_url' => 'https://m.media-amazon.com/images/I/61mw3l-aSJL._AC_UF894,1000_QL80_.jpg',
                'affiliate_link' => 'https://www.amazon.com.mx/Vintage-Walnut-Fashioned-Classic-Enhancement/dp/B0CPJ9GXXX',
                'category_id' => 3,
                'brand_id' => 1,
                'created_at' => Carbon::parse('2025-03-13 23:13:36'),
                'updated_at' => Carbon::parse('2025-03-13 23:13:36'),
            ],
            [
                'name' => 'Refrigerador retro rojo',
                'description' => 'Un refrigerador estilo populuxe en color rojo',
                'price' => 4495.00,
                'image_url' => 'https://bigchill.com/Images/Products/retrooriginalfridge-red.jpg?width=500',
                'affiliate_link' => 'https://bigchill.com/original-fridge.aspx?sku=21TF-CR&srsltid=AfmBOorRSrEFsYl8uo0NtxwKwJn30JMEI7KqRxMTUWRXW_ZTvvfNEbda',
                'category_id' => 2,
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Estufa retro',
                'description' => 'Una estufa con diseño populuxe en diferentes colores',
                'price' => 6895.00,
                'image_url' => 'https://bigchill.com/Images/Products/36RetroStove/StandardColors/Retro36StoveStraight-BeachBlue-Main.jpg?width=500',
                'affiliate_link' => 'https://bigchill.com/36-retro-stove.aspx',
                'category_id' => 2,
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tostadora retro',
                'description' => 'Una tostadora estilo populuxe en 2 colores diferentes',
                'price' => 175.00,
                'image_url' => 'https://bigchill.com/Images/Products/RetroToaster/Standard/RetroToaster-Cherry-Red-Main.jpg?width=500',
                'affiliate_link' => 'https://bigchill.com/retro-toaster.aspx',
                'category_id' => 2,
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lámpara de lava de los 60s',
                'description' => 'Astro Flame es una versión alimentada por velas de nuestro diseño clásico de 1963. Fabricamos Astro Flame íntegramente en Gran Bretaña. Las piezas metálicas se hilan y pulen a mano, y cada botella se llena en nuestra fábrica. Astro Flame funciona a la perfección con las velas Mathmos.',
                'price' => 110.00,
                'image_url' => 'https://network.mathmos.com/app/uploads/sites/8/2024/10/Mathmos_astro_flame_candle_lava_lamp_clear_green-1.jpg',
                'affiliate_link' => 'https://mathmos.es/producto/lampara-de-lava-astro-flame-velas/',
                'category_id' => 2,
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tocadiscos de vinilo',
                'description' => 'Tocadiscos de vinilo con receptor Bluetooth integrado y 2 altavoces estéreo, reproductor de discos retro portátil de 3 velocidades y 3 tamaños para entretenimiento y decoración del hogar',
                'price' => 1151.00,
                'image_url' => 'https://m.media-amazon.com/images/I/81u6HXFm0mL._AC_UF894,1000_QL80_.jpg',
                'affiliate_link' => 'https://www.amazon.com.mx/Kedok-Tocadiscos-reproductor-velocidades-entretenimiento/dp/B07N3WYLKZ/ref=asc_df_B07N3WYLKZ?mcid=876858894a4c305ab93f2261e6e30973&tag=gledskshopmx-20&linkCode=df0&hvadid=709953053675&hvpos=&hvnetw=g&hvrand=2842955147025495205&hv',
                'category_id' => 3,
                'brand_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Polo para hombre estilo de los 70s',
                'description' => 'Camisa polo para caballero en color café con un estilo de los años 70s',
                'price' => 613.38,
                'image_url' => 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSx1xqyw0JinPGa0lm4YBGZQ-ul3sJgTQG5ZAXYpl7LngKW1j7ApLJ7ZbGGleC75NH-todaWLRaAJFWXVq_b3QTW0c-5F7BHUZ5vTMvOIJGOT3poCaxkPRKTXX1DJqtnjRqK9k1kQ&usqp=CAc',
                'affiliate_link' => 'https://www.oxknit.com/products/men-70s-brown-retro-knit-polo?variant=44219747696834&currency=USD&gad_source=1&gad_campaignid=20438603977&gclid=Cj0KCQjwotDBBhCQARIsAG5pinNJWFI1iXS2hSZS_zrCISy439KwUAnu3Ml8iAuzka0UGAwsiDOyIsAaAm3VEALw_wcB',
                'category_id' => 1,
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Camisa de distintos colores',
                'description' => 'Camisa de algodón y lino con estampado clásico para hombre, estilo antiguo, estilo casual, manga corta con botones',
                'price' => 491.84,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcT0xgnx2qaYioktnXTJ_yhcWcqehUHSCAfJ_8nGXdshMcxCwpUjtmvp-htGX8TojBstLa0UwV_1gcZoX8q-trIe-MsvxEGNbOdKVBZRScDYgsHDPsdH_OPime7joBRa-HZoz0KOb5ayj2c&usqp=CAc',
                'affiliate_link' => 'https://www.amazon.com.mx/PARKLEES-algod%C3%B3n-estampado-cl%C3%A1sico-antiguo/dp/B0CRKF93LV/ref=asc_df_B0CRKF93LV?mcid=e9fe8ec8ece239c3842dd72bedd657f7&tag=gledskshopmx-20&linkCode=df0&hvadid=725408864835&hvpos=&hvnetw=g&hvrand=6397105325293422131&hvpone',
                'category_id' => 1,
                'brand_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Vestido estilo retro de los 50s',
                'description' => 'Vestido de cóctel para mujer, estilo retro clásico de los años 50, manga 3/4, cuello cuadrado, para cóctel',
                'price' => 1042.34,
                'image_url' => 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSeBtvXp049i4wzcruU-YxPFjVTSmr9e6z6psgMy39x9ui_bIUvpf5ZkA5kAgMi9BPH4dlhssRBqsW1t7hBWpdm5Sbvivxkbe9jUk7lvV5E',
                'affiliate_link' => 'https://www.amazon.com.mx/MUXXN-Vestido-cl%C3%A1sico-cuadrado-Borgo%C3%B1a/dp/B0CC26XR93?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&smid=A2OOTYP7Z383NK&th=1&psc=1',
                'category_id' => 1,
                'brand_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Teclado mecánico retro',
                'description' => 'Teclado mecánico retro, Bluetooth/2.4G/USB-C Teclado para juegos intercambiable en caliente con 87 teclas, botones dobles y Super Stick para Windows y Android',
                'price' => 1670.39,
                'image_url' => 'https://m.media-amazon.com/images/I/71yE77UAvxL.jpg',
                'affiliate_link' => 'https://www.amazon.com.mx/Teclado-mec%C3%A1nico-Bluetooth-intercambiable-caliente/dp/B0CYSQWYZP/ref=asc_df_B0CYSQWYZP?mcid=259160cdba59383aa9b95e6743ae4a2b&tag=gledskshopmx-20&linkCode=df0&hvadid=709846429635&hvpos=&hvnetw=g&hvrand=6061722186056628725&hvp',
                'category_id' => 3,
                'brand_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Camisa de cuello retro',
                'description' => 'Camisa para hombre con cuello y un estilo inspirado en los años 70s',
                'price' => 615.67,
                'image_url' => 'https://www.oxknit.com/cdn/shop/products/polo341.jpg?v=1663743680&width=1080',
                'affiliate_link' => 'https://www.oxknit.com/el/products/men-70s-knit-polo-rust-orange',
                'category_id' => 1,
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Camisa polo apricot knit',
                'description' => 'Camisa polo estilo retro 100% algodón',
                'price' => 961.46,
                'image_url' => 'https://cdn.shoplightspeed.com/shops/661229/files/66338638/1024x1024x1/oxknit-apricot-knit-polo-shirt.jpg',
                'affiliate_link' => 'https://www.peepasps.com/apricot-knit-polo-shirt.html',
                'category_id' => 1,
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lavavajillas retro',
                'description' => 'Un lavavajillas estilo retro disponible en diferentes colores',
                'price' => 2195.00,
                'image_url' => 'https://bigchill.com/Images/Products/RetroDishwasher/StandardColors/RetroDishwasher-BeachBlue-Main.jpg?width=500',
                'affiliate_link' => 'https://bigchill.com/retro-dishwasher.aspx',
                'category_id' => 2,
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Horno retro de pared',
                'description' => 'Horno de pared eléctrico estilo retro',
                'price' => 4195.00,
                'image_url' => 'https://bigchill.com/Images/Products/30WallOven/StandardColors/RetroWallOven-CherryRed-Main.jpg?width=500',
                'affiliate_link' => 'https://bigchill.com/30-electric-wall-oven.aspx',
                'category_id' => 2,
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mesa auxiliar retro',
                'description' => 'Mesa auxiliar retro con dos estantes para discos de vinilo y soporte para plantas',
                'price' => 1009.00,
                'image_url' => 'https://i.etsystatic.com/5677566/r/il/1b0729/5184937164/il_1588xN.5184937164_feq2.jpg',
                'affiliate_link' => 'https://www.etsy.com/mx/listing/1524544814/mesa-auxiliar-retro-con-dos-estantes?ls=s&ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=retro+furniture&ref=sr_gallery-1-4&etp=1&sts=1&content_source=ce87e78fa9dfda2ec7a8b727828f6',
                'category_id' => 2,
                'brand_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mesita de noche retro',
                'description' => 'Mesita de noche con bultos para un diseño interior único – Mini bar para un diseño interior moderno – Regalos personalizados',
                'price' => 7022.99,
                'image_url' => 'https://i.etsystatic.com/18692493/r/il/d179de/5025446546/il_1588xN.5025446546_tt3q.jpg',
                'affiliate_link' => 'https://www.etsy.com/mx/listing/1410501566/mesita-de-noche-con-bultos-para-un?ls=a&ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=retro+furniture&ref=sc_gallery-1-7&pro=1&plkey=6047f4f01835b22ab5b45874b618112c9091cda8%3A141',
                'category_id' => 2,
                'brand_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chaqueta blue rising',
                'description' => 'Chaqueta original Blue Rising Sun de Classic Rock Couture / Chaqueta bomber retro acolchada azul marino de los años 70 / Satén de esquí ligero vintage',
                'price' => 3737.37,
                'image_url' => 'https://i.etsystatic.com/8446390/r/il/e6413e/1231590461/il_1588xN.1231590461_akoa.jpg',
                'affiliate_link' => 'https://www.etsy.com/mx/listing/509134500/chaqueta-original-blue-rising-sun-de?ls=a&ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=&ref=sc_gallery-1-1&etp=1&plkey=9e3399324758e98b666ce24e6f36e7bbefb86984%3A509134500',
                'category_id' => 1,
                'brand_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chaqueta dodgers',
                'description' => 'Vintage USA Dodgers Béisbol MLB Starter Bomber Chaqueta',
                'price' => 6896.55,
                'image_url' => 'https://i.etsystatic.com/13880609/r/il/272b7e/4587123419/il_1588xN.4587123419_3f21.jpg',
                'affiliate_link' => 'https://www.etsy.com/mx/listing/1397515625/vintage-usa-dodgers-beisbol-mlb-starter?ls=a&ga_order=most_relevant&ga_search_type=vintage&ga_view_type=gallery&ga_search_query=&ref=sc_gallery-1-3&plkey=7d7509f3b75dbed3cffc201e376d9b946151599c%3A1397515625',
                'category_id' => 1,
                'brand_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chaqueta David Bowie',
                'description' => 'David Bowie Ziggie Stardust Chaqueta vaquera estilo camionero personalizada, estilo vintage de los años 80 y 90, tallas S a XXL',
                'price' => 1040.82,
                'image_url' => 'https://i.etsystatic.com/34657171/r/il/e4127b/4006869589/il_1588xN.4006869589_iwi4.jpg',
                'affiliate_link' => 'https://www.etsy.com/mx/listing/1255389129/david-bowie-ziggie-stardust-chaqueta?ls=a&ga_order=most_relevant&ga_search_type=vintage&ga_view_type=gallery&ga_search_query=&ref=sc_gallery-1-10&bes=1&plkey=049d5ed4b9301c1e92b4f6fac40dc2a46cc580db%3A1255389129',
                'category_id' => 1,
                'brand_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chaqueta universitaria',
                'description' => 'Chaqueta vaquera universitaria GMC Swingsters vintage',
                'price' => 2525.25,
                'image_url' => 'https://i.etsystatic.com/56643612/r/il/ecef6a/6891636058/il_1588xN.6891636058_gh69.jpg',
                'affiliate_link' => 'https://www.etsy.com/mx/listing/4311199586/chaqueta-vaquera-universitaria-gmc?ls=a&ga_order=most_relevant&ga_search_type=vintage&ga_view_type=gallery&ga_search_query=&ref=sc_gallery-1-11&plkey=2e988c11456bcebff236917a611ccddae8b0dee1%3A4311199586',
                'category_id' => 1,
                'brand_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}